### ISSUE TITLE
Project description is misleading.

### ISSUE THREAD

**Issue by vi** [fprasx/peapod#1]
Repository description, beginning of README, post on URLO, etc. describe `peapod` as a compact storage for enums, while in fact it is a compact storage for *sequences* of enums.

Initially I assumed it would store single instances of complicated, deeply nested enums efficiently (and that storage form can be used e.g. as keys for hash maps).
But in fact is seems to support only one data structure: vector. And nested enums are not mentioned in the docs, so I assume they are not supported (or not compacted).

I think it would be better to style project as "compact storage for Vec\<enums>" (or something like that) and edit all those mentions.

**Comment by fprasx** [comment]
Hi, when I wrote everything I didn't realize my wording could be interpreted differently - thanks for pointing that out! I'll try to come up with less ambiguous wording; I think your "compact storage for Vec<enums>" is a good start.
