### ISSUE TITLE
Panics and integer overflows can create untagged values in a `Peapod`

### ISSUE THREAD

**Issue by LegionMammal978** [fprasx/peapod#2]
The `Peapod` type has the safety invariant that all tags in `tags` must match the corresponding values in `data`. In certain scenarios, the number of values can end up being greater than the number of tags. This cannot result in unsoundness by itself (only panics), except that adding many untagged values to `data` could possibly cause `data.len() * T::BITS` to overflow.

I've identified two situations that create untagged values.

1. On 32-bit targets, a `BitVec` can only store `0x1fffffff` bits. After that, `BitVec::push()` will panic. Since `Peapod::push()` pushes the value to `data` before extending `tags`, catching the panic reveals an untagged value at the end of the `Peapod`. To illustrate:
```rust
/*
[dependencies]
peapod = "=0.1.8"

cargo run -r --target i686-unknown-linux-gnu
*/

use peapod::{Peapod, Phenotype};
use std::panic::{self, AssertUnwindSafe};

#[derive(Phenotype)]
enum Enum {
    Variant,
}

fn catch(f: impl FnOnce()) {
    panic::catch_unwind(AssertUnwindSafe(f)).unwrap_err();
}

fn main() {
    let mut pp = Peapod::new();
    for _ in 0..0x1fffffff {
        pp.push(Enum::Variant);
    }
    catch(|| pp.push(Enum::Variant));
    pp.pop(); // panics
}
```

2. On profiles with `overflow-checks = false`, the `len * T::BITS` calculation in `Peapod::truncate()` can overflow, causing `tags` to be truncated shorter than `data`. To illustrate:
```rust
/*
[dependencies]
peapod = "=0.1.8"

cargo run -r
*/

use peapod::{Peapod, Phenotype};

#[derive(Phenotype)]
enum Enum {
    Variant0,
    Variant1,
    Variant2,
}

fn main() {
    let mut pp = Peapod::new();
    pp.push(Enum::Variant0);
    pp.truncate(usize::MAX / 2 + 1);
    pp.pop(); // panics
}
```

**Comment by fprasx** [comment]
Thank you for this! :))

If you'd like you can submit a pull.

I'll look more into this and properly document and fix everything as soon as I have time (semester just started).

Edit: should be fixed in [5bff4f1](https://github.com/fprasx/peapod/commit/5bff4f102fa64401f1d87e9343c9541947fdaeb3)

**Comment by LegionMammal978** [comment]
That solves the correctness issues. At worst, you'd have either a partial valueless tag due to `self.tags.push()` panicking, or any number of full valueless tags from the `self.data.push()` failing. This might cause some confusion with the `PartialEq` and `Debug` implementations, which read the entirety of `self.tags` instead of stopping at `self.data.len() * T::BITS`. A proper solution might be to `reserve()` the necessary space in both vectors before pushing anything.

**Comment by fprasx** [comment]
Yes, that seems right. We could also `assert` that pushing won't exceed maximum capacity.
